spring:
  datasource:
    url: jdbc:h2:mem:estoquedb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  docker:
    enabled: false
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
  h2:
    console:
    enabled: true
    path: /h2-console
server:
  port: 8080